# Generated by Django 3.0.3 on 2020-03-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('login_num', models.IntegerField()),
            ],
        ),
    ]
