# Generated by Django 3.0.3 on 2020-03-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('pro_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('cre_time', models.DateField(auto_now_add=True)),
                ('theme', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=300)),
            ],
        ),
    ]
