# Generated by Django 3.0.3 on 2020-03-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro',
            name='cre_time',
        ),
    ]
