# Generated by Django 3.0.3 on 2020-03-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_pro_cre_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='content',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='pro',
            name='theme',
            field=models.CharField(max_length=100),
        ),
    ]
