# Generated by Django 3.0.3 on 2020-04-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20200326_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ans',
            fields=[
                ('ans_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('to_pro_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=10)),
                ('ans_content', models.CharField(max_length=300)),
            ],
        ),
    ]
